
tasks:
  - init: sudo apt update
    command: |
        pyenv install 3.11.1 &&
        pyenv global 3.11.1 &&
        npm i nodemon --global &&
        pip install -r requirements.txt


vscode:
  extensions:
    - ms-python.python
    - whizkydee.material-palenight-theme
    - ms-pyright.pyright
